Plan = {
  "Bank": {
    Ex: {
      Legs: [
         {
          name: "Leg press",
          type: "Legs",
          where: "Machine",
          wraming: true,
          reps: 10,
          sets: 3,
          score: 0.1,
          id: 10,
        },
        {
          name: "Squat",
          type: "Legs",
          where: "Free",
          wraming: true,
          reps: 8,
          sets: 3,
          score: 0.34,
          id: 11,
        },
         {
          name: "Launch",
          type: "Legs",
          where: "Free",
          wraming: true,
          reps: 8,
          sets: 2,
          score: 0.46,
          id: 12,
        },
         {
          name: "Leg ext",
          type: "Legs",
          where: "Machine",
          wraming: false,
          reps: 12,
          sets: 3,
          score: 0.05,
          id: 13,
        },
         {
          name: "Leg flex",
          type: "Legs",
          where: "Machine",
          wraming: false,
          reps: 12,
          sets: 3,
          score: 0.05,
          id: 14,
        },
         {
          name: "Gastru press",
          type: "Legs",
          where: "Machine",
          wraming: false,
          reps: 12,
          sets: 2,
          score: 0.03,
          id: 15,
        },
    ],
      Back: [
         {
          name: "Pull up cable",
          type: "Back",
          where: "Cable pull",
          wraming: true,
          reps: 10,
          sets: 3,
          score: 0.15,
          id: 20,
        },
         {
          name: "Pull up free",
          type: "Back",
          where: "Free",
          wraming: true,
          reps: 5,
          sets: 3,
          score: 0.4,
          id: 21,
        },
         {
          name: "Raw DB",
          type: "Back",
          where: "Free",
          wraming: false,
          reps: 8,
          sets: 2,
          score: 0.25,
          id: 22,
        },
        {
          name: "Raw bar",
          type: "Back",
          where: "Free",
          wraming: true,
          reps: 8,
          sets: 3,
          score: 0.37,
          id: 23,
        },
         {
          name: "Raw seat",
          type: "Back",
          where: "Cable pull",
          wraming: false,
          reps: 8,
          sets: 2,
          score: 0.15,
          id: 24,
        },
         {
          name: "Pull over DB",
          type: "Back",
          where: "Free",
          wraming: false,
          reps: 8,
          sets: 2,
          score: 0.15,
          id: 25,
        },
         {
          name: "Deadlift",
          type: "Back",
          where: "Free",
          wraming: true,
          reps: 6,
          sets: 3,
          score: 0.4,
          id: 26,
        },
    ],
      Chest: [
         {
          name: "Bench press DB",
          type: "Chest",
          where: "Free",
          wraming: true,
          reps: 10,
          sets: 3,
          score: 0.3,
          id: 30,
        },
         {
          name: "Bench press bar",
          type: "Chest",
          where: "Free",
          wraming: true,
          reps: 8,
          sets: 3,
          score: 0.3,
          id: 31,
        },

         {
          name: "Fly's DB",
          type: "Chest",
          where: "Free",
          wraming: false,
          reps: 8,
          sets: 2,
          score: 0.25,
          id: 32,
        },

         {
          name: "Fly's machine",
          type: "Chest",
          where: "Machine",
          wraming: false,
          reps: 12,
          sets: 3,
          score: 0.1,
          id: 33,
        },
         {
          name: "Dip",
          type: "Chest",
          where: "Free",
          wraming: false,
          reps: 5,
          sets: 2,
          score: 0.35,
          id: 34,
        },
         {
          name: "Fly's cable(-)",
          type: "Chest",
          where: "Cable pull",
          wraming: false,
          reps: 12,
          sets: 2,
          score: 0.1,
          id: 35,
        },
    ],
      Deltoid: [
         {
          name: "Shoulder press",
          type: "Deltoid",
          where: "Free",
          wraming: true,
          reps: 8,
          sets: 3,
          score: 0.15,
          id: 40,
        },
         {
          name: "Fl'ys DB",
          type: "Deltoid",
          where: "Free",
          wraming: false,
          reps: 8,
          sets: 2,
          score: 0.1,
          id: 41,
        },
    ],
      Triceps: [
         {
          name: "Triceps ext",
          type: "Triceps",
          where: "Cable pull",
          wraming: true,
          reps: 10,
          sets: 3,
          score: 0.1,
          id: 50,
        },
         {
          name: "Dip",
          type: "Triceps",
          where: "Free",
          wraming: false,
          reps: 5,
          sets: 3,
          score: 0.35,
          id: 51,
        },
         {
          name: "french DB",
          type: "Triceps",
          where: "Free",
          wraming: true,
          reps: 10,
          sets: 3,
          score: 0.12,
          id: 52,
        },
         {
          name: "french machine",
          type: "Triceps",
          where: "Machine",
          wraming: true,
          reps: 10,
          sets: 3,
          score: 0.1,
          id: 53,
        },
    ],
      Biceps: [
         {
          name: "Biceps flex DB",
          type: "Biceps",
          where: "Free",
          wraming: true,
          reps: 10,
          sets: 3,
          score: 0.15,
          id: 60,
        },
         {
          name: "Biceps 60 flex DB",
          type: "Biceps",
          where: "Free",
          wraming: true,
          reps: 10,
          sets: 3,
          score: 0.15,
          id: 61,
        },
         {
          name: "Bi flex machine",
          type: "Biceps",
          where: "Free",
          wraming: true,
          reps: 12,
          sets: 3,
          score: 0.12,
          id: 62,
        },
        {
          name: "Bi flex bar",
          type: "Biceps",
          where: "Free",
          wraming: true,
          reps: 8,
          sets: 3,
          score: 0.17,
          id: 63,
        },
    ],
    },
  },
};
